CREATE USER ERS
IDENTIFIED BY p4ssw0rd
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to ERS;
GRANT resource to ERS;
GRANT create session to ERS;
GRANT create table to ERS;
GRANT create view to ERS;

conn ERS/p4ssw0rd

create table EMPLOYEE(
    EMP_ID integer,
    EMP_NAME varchar2(20) not null,
    EMP_PASSWORD varchar2(32) not null,
    EMP_DPT integer default 1 not null,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMP_ID)
);

create sequence SQ_EMP_PK
    start with 1
    minvalue 1
    maxvalue 1000;

create trigger TR_EMPLOYEE_BI
before insert on EMPLOYEE
    for each row
        begin
            select SQ_EMP_PK.NEXTVAL
            into :New.EMP_ID from DUAL;
end;
/


create table REIMBURSEMENT(
    REIM_ID integer,
    EMP_ID integer not null,
    REIM_REASON varchar2(200),
    REIM_AMOUNT number(10,2) DEFAULT 0.00,
    DPT_ID integer not null,
    REIM_APPROVAL char(1) default 0 not null,
    REIM_COMPLETE char(1) default 0 not null,
    CONSTRAINT PK_REIMBURSEMENT PRIMARY KEY(REIM_ID),
    CONSTRAINT CK_BOOL_REIMBURSEMENT_APRVL CHECK (REIM_APPROVAL = 0 or  REIM_APPROVAL = 1),
    CONSTRAINT CK_BOOL_REIMBURSEMENT_CMP CHECK (REIM_COMPLETE = 0 or  REIM_COMPLETE = 1) 
);

create sequence SQ_REIM_PK
    start with 1
    minvalue 1
    maxvalue 10000;

create trigger TR_REIM_BI
before insert on REIMBURSEMENT
    for each row
        begin
            select SQ_REIM_PK.NEXTVAL
            into :NEW.REIM_ID from DUAL;
end;
/

create table DEPARTMENT(
    DPT_ID integer,
    DPT_NAME varchar(25) not null,
    MGR_ID integer,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DPT_ID)
);


create sequence SQ_DPT_PK
    start with 1
    minvalue 1
    maxvalue 20;

create trigger TR_DEPARTMENT_BI
before insert on DEPARTMENT
    for each row
        begin
            select SQ_DPT_PK.NEXTVAL
            into :New.DPT_ID from DUAL;
end;
/

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_DPT FOREIGN KEY(EMP_DPT) REFERENCES DEPARTMENT(DPT_ID);

ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_MGR FOREIGN KEY(MGR_ID) REFERENCES EMPLOYEE(EMP_ID);

ALTER TABLE REIMBURSEMENT ADD (CONSTRAINT FK_REIMBURSEMENT_DEPARTMENT FOREIGN KEY(DPT_ID) REFERENCES DEPARTMENT(DPT_ID),
CONSTRAINT FK_REIMBURSEMENT_EMPLOYEE FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID));

commit;

DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;
DROP TABLE REIMBURSEMENT;



INSERT INTO DEPARTMENT (DPT_NAME) VALUES ('Niue');
INSERT INTO DEPARTMENT (DPT_NAME) VALUES ('Mongolia');
INSERT INTO DEPARTMENT (DPT_NAME) VALUES ('Saint Lucia');
INSERT INTO DEPARTMENT (DPT_NAME) VALUES ('Brazil');
INSERT INTO DEPARTMENT (DPT_NAME) VALUES ('Sweden');
INSERT INTO DEPARTMENT (DPT_NAME) VALUES ('Tajikistan');
INSERT INTO DEPARTMENT (DPT_NAME) VALUES ('Belgium');
INSERT INTO DEPARTMENT (DPT_NAME) VALUES ('Isle of Man');
INSERT INTO DEPARTMENT (DPT_NAME) VALUES ('Pakistan');
INSERT INTO DEPARTMENT (DPT_NAME) VALUES ('Ghana');
INSERT INTO DEPARTMENT (DPT_NAME) VALUES ('Reunion');



INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Lavinia','FRY37CYD4KJ',3);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Charlotte','AYX78MSD8JM',2);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Delilah','LVW99JCC1WU',2);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Velma','HLD10IVW9RN',10);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Ray','KHJ99AVL4FC',9);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Walker','CLC01TRC5CW',2);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Dante','DZN56AUN7BA',10);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Xander','NCM20YUU8QX',10);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Uriah','OAB72UHV4GV',7);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Damon','AMG39RCV2JZ',9);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Ishmael','AKR17XZC3LU',4);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Celeste','KHC29XKP7RY',1);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Stuart','ZXJ88DHH1SY',6);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Stuart','QGI36SPC2JR',10);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Aubrey','OAK89UAV4MF',7);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Nathaniel','HNN40GAW0ZO',6);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Quail','LSB45GLN4SQ',7);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Aline','CWO79KYH5FE',1);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Sierra','KGC42SIL3JK',10);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Jermaine','VUL88DFU3FL',3);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Aimee','QAS64WIF8EV',6);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Benedict','IYT15VBC3EM',2);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Nina','HDS00UYJ7VH',8);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Renee','ZCI62FDF4SX',2);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Richard','CSL83UFT9HC',1);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Harriet','SZC67ZCV4FQ',4);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Alan','MAX77EJV1DH',5);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Merritt','JFH51XJP6UH',4);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Jillian','FLT99HXN5BJ',8);
INSERT INTO EMPLOYEE (EMP_NAME,EMP_PASSWORD,EMP_DPT) VALUES ('Dakota','KCW64DXE0ZO',9);


UPDATE DEPARTMENT set MGR_ID = 1 where DPT_ID=3;
UPDATE DEPARTMENT set MGR_ID = 1 where DPT_ID=10;
UPDATE DEPARTMENT set MGR_ID = 1 where DPT_ID=9;
UPDATE DEPARTMENT set MGR_ID = 1 where DPT_ID=2;
UPDATE DEPARTMENT set MGR_ID = 1 where DPT_ID=7;
UPDATE DEPARTMENT set MGR_ID = 1 where DPT_ID=4;
